import 'package:flutter/material.dart';

// ─────────────────────────── Data model ─────────────────────────────────
class RecipeIngredient {
  final String name;
  final String amount;
  final IconData icon;
  const RecipeIngredient(this.name, this.amount, this.icon);
}

enum RecipeCategory { hot, lowCal, kids, soup, curry }

class RecipeData {
  final String name, kcal;
  final String imageUrl;
  final List<Color> gradient;
  final String prepTime;
  final String servings;
  final RecipeCategory category;
  final List<RecipeIngredient> ingredients;
  const RecipeData(
    this.name,
    this.kcal,
    this.imageUrl,
    this.gradient, {
    required this.category,
    required this.prepTime,
    required this.servings,
    required this.ingredients,
  });
}

// ─────────────────────────── All Recipes ────────────────────────────────
const allRecipes = <RecipeData>[
  // ── 🔥 HOT ──
  RecipeData(
    'Cast-Iron Steak',
    '760 kcal',
    'https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=400&q=80',
    [Color(0xFF5D4037), Color(0xFF8D6E63)],
    category: RecipeCategory.hot,
    prepTime: '25 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Ribeye steak', '300g', Icons.set_meal),
      RecipeIngredient('Butter', '2 tbsp', Icons.opacity),
      RecipeIngredient('Garlic cloves', '3 cloves', Icons.grass),
      RecipeIngredient('Fresh rosemary', '2 sprigs', Icons.eco),
      RecipeIngredient('Sea salt', '1 tsp', Icons.grain),
      RecipeIngredient('Black pepper', '½ tsp', Icons.grain),
      RecipeIngredient('Olive oil', '1 tbsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Spicy Buffalo Wings',
    '620 kcal',
    'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&q=80',
    [Color(0xFFBF360C), Color(0xFFE64A19)],
    category: RecipeCategory.hot,
    prepTime: '40 min',
    servings: '3',
    ingredients: [
      RecipeIngredient('Chicken wings', '500g', Icons.set_meal),
      RecipeIngredient('Hot sauce', '4 tbsp', Icons.local_fire_department),
      RecipeIngredient('Butter', '2 tbsp', Icons.opacity),
      RecipeIngredient('Garlic powder', '1 tsp', Icons.grain),
      RecipeIngredient('Paprika', '1 tsp', Icons.grain),
      RecipeIngredient('Salt', '½ tsp', Icons.grain),
      RecipeIngredient('Vegetable oil', '2 tbsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Spicy Korean Fried Rice',
    '580 kcal',
    'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80',
    [Color(0xFFC62828), Color(0xFFEF5350)],
    category: RecipeCategory.hot,
    prepTime: '20 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Cooked rice', '300g', Icons.grain),
      RecipeIngredient(
        'Gochujang paste',
        '2 tbsp',
        Icons.local_fire_department,
      ),
      RecipeIngredient('Kimchi', '100g', Icons.eco),
      RecipeIngredient('Egg', '2 pcs', Icons.egg),
      RecipeIngredient('Sesame oil', '1 tbsp', Icons.water_drop),
      RecipeIngredient('Green onion', '2 stalks', Icons.grass),
      RecipeIngredient('Soy sauce', '1 tbsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Chili Con Carne',
    '690 kcal',
    'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=400&q=80',
    [Color(0xFF6D1A0E), Color(0xFFB71C1C)],
    category: RecipeCategory.hot,
    prepTime: '50 min',
    servings: '4',
    ingredients: [
      RecipeIngredient('Ground beef', '400g', Icons.set_meal),
      RecipeIngredient('Kidney beans', '200g', Icons.grain),
      RecipeIngredient('Canned tomatoes', '400g', Icons.circle),
      RecipeIngredient('Chili powder', '2 tsp', Icons.local_fire_department),
      RecipeIngredient('Cumin', '1 tsp', Icons.grain),
      RecipeIngredient('Onion', '1 large', Icons.circle),
      RecipeIngredient('Garlic', '3 cloves', Icons.grass),
    ],
  ),

  // ── 🌿 LOW-CAL ──
  RecipeData(
    'Crisp Cucumber Protein Bowl',
    '320 kcal',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    [Color(0xFF2E7D32), Color(0xFF66BB6A)],
    category: RecipeCategory.lowCal,
    prepTime: '10 min',
    servings: '1',
    ingredients: [
      RecipeIngredient('Greek yogurt', '150g', Icons.water_drop),
      RecipeIngredient('Cucumber', '1 medium', Icons.grass),
      RecipeIngredient('Chickpeas', '80g', Icons.grain),
      RecipeIngredient('Cherry tomatoes', '8 pcs', Icons.circle),
      RecipeIngredient('Fresh dill', '1 tbsp', Icons.eco),
      RecipeIngredient('Lemon juice', '1 tbsp', Icons.wb_sunny),
      RecipeIngredient('Olive oil', '1 tsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Fresh Green & Protein Plate',
    '280 kcal',
    'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
    [Color(0xFF1B5E20), Color(0xFF43A047)],
    category: RecipeCategory.lowCal,
    prepTime: '15 min',
    servings: '1',
    ingredients: [
      RecipeIngredient('Grilled tofu', '100g', Icons.square),
      RecipeIngredient('Edamame', '60g', Icons.grass),
      RecipeIngredient('Spinach', '50g', Icons.eco),
      RecipeIngredient('Avocado', '½ piece', Icons.circle),
      RecipeIngredient('Quinoa', '80g', Icons.grain),
      RecipeIngredient('Sesame seeds', '1 tsp', Icons.grain),
      RecipeIngredient('Soy sauce', '1 tbsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Grilled Chicken Salad',
    '450 kcal',
    'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=400&q=80',
    [Color(0xFF558B2F), Color(0xFF8BC34A)],
    category: RecipeCategory.lowCal,
    prepTime: '30 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Chicken breast', '200g', Icons.set_meal),
      RecipeIngredient('Romaine lettuce', '100g', Icons.eco),
      RecipeIngredient('Cherry tomatoes', '10 pcs', Icons.circle),
      RecipeIngredient('Parmesan', '20g', Icons.grain),
      RecipeIngredient('Caesar dressing', '2 tbsp', Icons.water_drop),
      RecipeIngredient('Lemon', '½ piece', Icons.wb_sunny),
      RecipeIngredient('Black pepper', '¼ tsp', Icons.grain),
    ],
  ),
  RecipeData(
    'Tuna Zucchini Rolls',
    '210 kcal',
    'https://images.unsplash.com/photo-1562802378-063ec186a863?w=400&q=80',
    [Color(0xFF00695C), Color(0xFF26A69A)],
    category: RecipeCategory.lowCal,
    prepTime: '15 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Zucchini', '2 medium', Icons.grass),
      RecipeIngredient('Canned tuna', '120g', Icons.set_meal),
      RecipeIngredient('Cream cheese', '2 tbsp', Icons.opacity),
      RecipeIngredient('Lemon juice', '1 tsp', Icons.wb_sunny),
      RecipeIngredient('Dill', '1 tsp', Icons.eco),
      RecipeIngredient('Salt & pepper', 'to taste', Icons.grain),
    ],
  ),

  // ── 👶 KIDS ──
  RecipeData(
    'Avocado Toast',
    '380 kcal',
    'https://images.unsplash.com/photo-1603046891726-36bfd957e0bf?w=400&q=80',
    [Color(0xFF33691E), Color(0xFF8BC34A)],
    category: RecipeCategory.kids,
    prepTime: '10 min',
    servings: '1',
    ingredients: [
      RecipeIngredient('Sourdough bread', '2 slices', Icons.breakfast_dining),
      RecipeIngredient('Ripe avocado', '1 piece', Icons.circle),
      RecipeIngredient('Eggs', '2 eggs', Icons.egg),
      RecipeIngredient('Lemon juice', '1 tsp', Icons.wb_sunny),
      RecipeIngredient('Sea salt', '½ tsp', Icons.grain),
    ],
  ),
  RecipeData(
    'Mini Pancakes',
    '310 kcal',
    'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400&q=80',
    [Color(0xFFF57F17), Color(0xFFFFCC02)],
    category: RecipeCategory.kids,
    prepTime: '20 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('All-purpose flour', '150g', Icons.grain),
      RecipeIngredient('Milk', '200ml', Icons.water_drop),
      RecipeIngredient('Egg', '1 pc', Icons.egg),
      RecipeIngredient('Butter', '1 tbsp', Icons.opacity),
      RecipeIngredient('Sugar', '1 tbsp', Icons.grain),
      RecipeIngredient('Baking powder', '1 tsp', Icons.grain),
      RecipeIngredient('Maple syrup', '2 tbsp', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Cheesy Veggie Omelette',
    '340 kcal',
    'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400&q=80',
    [Color(0xFFF9A825), Color(0xFFFFD54F)],
    category: RecipeCategory.kids,
    prepTime: '15 min',
    servings: '1',
    ingredients: [
      RecipeIngredient('Eggs', '3 pcs', Icons.egg),
      RecipeIngredient('Cheddar cheese', '30g', Icons.grain),
      RecipeIngredient('Bell pepper', '¼ piece', Icons.circle),
      RecipeIngredient('Spinach', '20g', Icons.eco),
      RecipeIngredient('Milk', '2 tbsp', Icons.water_drop),
      RecipeIngredient('Butter', '1 tsp', Icons.opacity),
      RecipeIngredient('Salt', 'a pinch', Icons.grain),
    ],
  ),
  RecipeData(
    'Banana Oat Cookies',
    '220 kcal',
    'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80',
    [Color(0xFFE65100), Color(0xFFFF8A65)],
    category: RecipeCategory.kids,
    prepTime: '25 min',
    servings: '12',
    ingredients: [
      RecipeIngredient('Ripe banana', '2 pcs', Icons.circle),
      RecipeIngredient('Rolled oats', '200g', Icons.grain),
      RecipeIngredient('Honey', '2 tbsp', Icons.water_drop),
      RecipeIngredient('Chocolate chips', '50g', Icons.circle),
      RecipeIngredient('Cinnamon', '½ tsp', Icons.grain),
    ],
  ),

  // ── 🥄 SOUP ──
  RecipeData(
    'Creamy Tomato Soup',
    '290 kcal',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80',
    [Color(0xFFB71C1C), Color(0xFFE57373)],
    category: RecipeCategory.soup,
    prepTime: '30 min',
    servings: '3',
    ingredients: [
      RecipeIngredient('Canned tomatoes', '800g', Icons.circle),
      RecipeIngredient('Heavy cream', '100ml', Icons.water_drop),
      RecipeIngredient('Onion', '1 large', Icons.circle),
      RecipeIngredient('Garlic', '2 cloves', Icons.grass),
      RecipeIngredient('Basil', '5 leaves', Icons.eco),
      RecipeIngredient('Olive oil', '2 tbsp', Icons.water_drop),
      RecipeIngredient('Salt & pepper', 'to taste', Icons.grain),
    ],
  ),
  RecipeData(
    'Chicken Noodle Soup',
    '380 kcal',
    'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&q=80',
    [Color(0xFFE65100), Color(0xFFFFB74D)],
    category: RecipeCategory.soup,
    prepTime: '45 min',
    servings: '4',
    ingredients: [
      RecipeIngredient('Chicken thighs', '300g', Icons.set_meal),
      RecipeIngredient('Egg noodles', '150g', Icons.grain),
      RecipeIngredient('Carrot', '2 pcs', Icons.circle),
      RecipeIngredient('Celery', '2 stalks', Icons.grass),
      RecipeIngredient('Onion', '1 medium', Icons.circle),
      RecipeIngredient('Chicken broth', '1.5L', Icons.water_drop),
      RecipeIngredient('Thyme', '1 tsp', Icons.eco),
    ],
  ),
  RecipeData(
    'Miso Tofu Soup',
    '180 kcal',
    'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
    [Color(0xFF4E342E), Color(0xFF8D6E63)],
    category: RecipeCategory.soup,
    prepTime: '15 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('White miso paste', '3 tbsp', Icons.opacity),
      RecipeIngredient('Silken tofu', '200g', Icons.square),
      RecipeIngredient('Wakame seaweed', '10g', Icons.eco),
      RecipeIngredient('Green onion', '2 stalks', Icons.grass),
      RecipeIngredient('Dashi stock', '600ml', Icons.water_drop),
    ],
  ),
  RecipeData(
    'Pumpkin Coconut Soup',
    '260 kcal',
    'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&q=80',
    [Color(0xFFE65100), Color(0xFFFF7043)],
    category: RecipeCategory.soup,
    prepTime: '35 min',
    servings: '4',
    ingredients: [
      RecipeIngredient('Pumpkin', '600g', Icons.circle),
      RecipeIngredient('Coconut milk', '200ml', Icons.water_drop),
      RecipeIngredient('Vegetable broth', '500ml', Icons.water_drop),
      RecipeIngredient('Ginger', '1 tsp', Icons.grass),
      RecipeIngredient('Garlic', '2 cloves', Icons.grass),
      RecipeIngredient('Curry powder', '1 tsp', Icons.grain),
      RecipeIngredient('Salt & pepper', 'to taste', Icons.grain),
    ],
  ),

  // ── 🍛 CURRY ──
  RecipeData(
    'Butter Chicken Curry',
    '620 kcal',
    'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&q=80',
    [Color(0xFFE65100), Color(0xFFFF8F00)],
    category: RecipeCategory.curry,
    prepTime: '40 min',
    servings: '3',
    ingredients: [
      RecipeIngredient('Chicken breast', '400g', Icons.set_meal),
      RecipeIngredient('Butter', '3 tbsp', Icons.opacity),
      RecipeIngredient('Heavy cream', '150ml', Icons.water_drop),
      RecipeIngredient('Tomato puree', '200g', Icons.circle),
      RecipeIngredient('Garam masala', '2 tsp', Icons.grain),
      RecipeIngredient('Ginger paste', '1 tsp', Icons.grass),
      RecipeIngredient('Garlic paste', '1 tsp', Icons.grass),
    ],
  ),
  RecipeData(
    'Thai Green Curry',
    '540 kcal',
    'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&q=80',
    [Color(0xFF2E7D32), Color(0xFF66BB6A)],
    category: RecipeCategory.curry,
    prepTime: '30 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Coconut milk', '400ml', Icons.water_drop),
      RecipeIngredient('Green curry paste', '3 tbsp', Icons.eco),
      RecipeIngredient('Chicken or tofu', '300g', Icons.set_meal),
      RecipeIngredient('Thai basil', '10 leaves', Icons.eco),
      RecipeIngredient('Fish sauce', '2 tbsp', Icons.water_drop),
      RecipeIngredient('Lime juice', '1 tbsp', Icons.wb_sunny),
      RecipeIngredient('Jasmine rice', '200g', Icons.grain),
    ],
  ),
  RecipeData(
    'Japanese Katsu Curry',
    '710 kcal',
    'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&q=80',
    [Color(0xFF6D4C41), Color(0xFFA1887F)],
    category: RecipeCategory.curry,
    prepTime: '45 min',
    servings: '2',
    ingredients: [
      RecipeIngredient('Pork cutlet', '300g', Icons.set_meal),
      RecipeIngredient('Japanese curry roux', '100g', Icons.grain),
      RecipeIngredient('Potato', '2 medium', Icons.circle),
      RecipeIngredient('Carrot', '1 pc', Icons.circle),
      RecipeIngredient('Onion', '1 large', Icons.circle),
      RecipeIngredient('Panko breadcrumbs', '50g', Icons.grain),
      RecipeIngredient('Steamed rice', '300g', Icons.grain),
    ],
  ),
  RecipeData(
    'Chickpea Coconut Curry',
    '470 kcal',
    'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    [Color(0xFFFF6F00), Color(0xFFFFA000)],
    category: RecipeCategory.curry,
    prepTime: '25 min',
    servings: '3',
    ingredients: [
      RecipeIngredient('Chickpeas', '400g', Icons.grain),
      RecipeIngredient('Coconut milk', '300ml', Icons.water_drop),
      RecipeIngredient('Diced tomatoes', '200g', Icons.circle),
      RecipeIngredient('Spinach', '80g', Icons.eco),
      RecipeIngredient('Curry powder', '2 tsp', Icons.grain),
      RecipeIngredient('Turmeric', '½ tsp', Icons.grain),
      RecipeIngredient('Onion', '1 medium', Icons.circle),
    ],
  ),
];
