// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMbOQGr7_drMEUc4aOknrNA2YtyEFWGzM',
    appId: '1:462532276726:web:928c86819295d78554d7d7',
    messagingSenderId: '462532276726',
    projectId: 'healthsync-4775b',
    authDomain: 'healthsync-4775b.firebaseapp.com',
    storageBucket: 'healthsync-4775b.firebasestorage.app',
    measurementId: 'G-EJREX7H788',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCgTPCEQ6a_lnH8-iYiEWcmos2YCJyUWc',
    appId: '1:462532276726:android:a1080042553ff9d354d7d7',
    messagingSenderId: '462532276726',
    projectId: 'healthsync-4775b',
    storageBucket: 'healthsync-4775b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuSebH3B55R4hsSwd-gSSRQyoocznJjA',
    appId: '1:462532276726:ios:9ca6d5fe048ae16b54d7d7',
    messagingSenderId: '462532276726',
    projectId: 'healthsync-4775b',
    storageBucket: 'healthsync-4775b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANuSebH3B55R4hsSwd-gSSRQyoocznJjA',
    appId: '1:462532276726:ios:9ca6d5fe048ae16b54d7d7',
    messagingSenderId: '462532276726',
    projectId: 'healthsync-4775b',
    storageBucket: 'healthsync-4775b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMbOQGr7_drMEUc4aOknrNA2YtyEFWGzM',
    appId: '1:462532276726:web:1bb62a1c1efbc59e54d7d7',
    messagingSenderId: '462532276726',
    projectId: 'healthsync-4775b',
    authDomain: 'healthsync-4775b.firebaseapp.com',
    storageBucket: 'healthsync-4775b.firebasestorage.app',
    measurementId: 'G-PCNX35F6W2',
  );
}
